;AUTHOR: BRANDOM VEGA ENCISO

__CONFIG 0X3F71
#INCLUDE <p16f877a.inc>
List p=16f877a

ORG 0 

#DEFINE RS PORTC,4
#DEFINE EN PORTC,5
UNO_SET EQU 0X45
DOS_SET EQU 0X46
TMR_CARGA EQU .252
;VALORES DE DIGITOS
DIG1 EQU 0X50
DIG2 EQU 0X51
DIG3 EQU 0X52
DIG4 EQU 0X53
DIG5 EQU 0X54
DIG6 EQU 0X55
DIG7 EQU 0X56
DIG8 EQU 0X57
DIG9 EQU 0X58
DIG0 EQU 0X59
DIGGATO EQU 0X5A

CONTADOR EQU 0X5C
CONTADORLIMITE EQU 0X5D
COMPARADORLIMITE EQU 0X5E
MODOPASSWORD EQU 0X5F
DIG1TEST EQU 0X60
DIG2TEST EQU 0X61
DIG3TEST EQU 0X62
DIG4TEST EQU 0X63

ABRIROADMIN EQU 0X64
IDENTIFICADOR EQU 0X65
STATE EQU 0X66

BSF STATUS,5
CLRF TRISC
MOVLW B'11110000'
MOVWF TRISB
MOVLW B'00000111'
MOVWF OPTION_REG
BCF STATUS,5
BCF STATUS,0
CLRF DIG1


REINICIO


CLRF PORTC
CALL INIT
CALL LIMPIEZA
CLRF PORTC
CALL HOLASET1
CALL BIENVENIDOSET1
CLRF UNO_SET
CLRF DOS_SET
CLRF MODOPASSWORD
CLRF ABRIROADMIN
	CLRF CONTADORLIMITE
	CLRF COMPARADORLIMITE
	;PERMITO EL CURSOR
	MOVLW B'00000' ;ASIGNO LA POSICION DE ESCRITURA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'01100' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
;--------------MENSAJE INICIAL MOVIEMIENTO----------
INICIO 
	MOVLW .14
	MOVWF 0X40
SEGURO
	DECFSZ 0X40,1
	GOTO ROTACION
	BSF STATUS,0
ENTRA
	MOVLW B'01101' ;ESCONDO EL POSIBLE MENSAJE
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00101'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	;ESPERO LAS RESPUESTA
	CALL TECLADO
	BTFSS STATUS,0 ;ES 1?
	GOTO CONTINUAR ;NO
	GOTO ENTRA	;SI
ROTACION
	CALL MENSAJE
	CALL TIEMPO
GOTO SEGURO
;----PARTE 2------
CONTINUAR	;LLAMADA DE LINEAS
	CLRF UNO_SET
	CLRF DOS_SET
	CALL LIMPIEZA
	CALL LINEAUNO
	MOVLW B'01100' ;ASIGNO LA SEGUNDA LINEA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00000' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL LINEADOS
	CLRF UNO_SET
	CALL TIEMPO
	BCF STATUS,0
	;ESCONDO EL NUMERO RESPUESTA	
	MOVLW B'01101' ;ASIGNO LA SEGUNDA LINEA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00000' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
CONTRASEÑA	;ESPERA LA RESPUESTA 1> O 2>
	CALL TECLADO
	MOVFW UNO_SET
	XORLW .20
	BTFSC STATUS,2;
	GOTO ABRIR
	
	MOVFW DOS_SET
	XORLW .21
	BTFSC STATUS,2
	GOTO MENU
GOTO CONTRASEÑA
;----OPEN DOOR------
ABRIR
	CALL LIMPIEZA
	MOVLW B'01000' ;ASIGNO LA POSICION
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00100' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	;password
	CALL PASSWORD
	MOVLW B'01100' ;ASIGNO LA POSICION DE ESCRITURA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00101' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	;PERMITO EL CURSOR
	MOVLW B'00000' ;ASIGNO LA POSICION DE ESCRITURA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'01111' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	;LIMPIO LO QUE SE USARÁ PARA EVITAR ERRORES
	BCF STATUS,2
	CLRF DIG0
	CLRF DIG1
	CLRF DIG2
	CLRF DIG3
	CLRF DIG4
	CLRF DIG5
	CLRF DIG6
	CLRF CONTADOR
	CLRF CONTADORLIMITE
	CLRF COMPARADORLIMITE
	BCF STATUS,2


	MOVLW 0XFF ;0X00 PARA NUMEROS 0XFF PARA PASSWORD
	MOVWF MODOPASSWORD
	CLRF PORTC
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
TESTD1 ;HORA  DE VERIFICAR LOS DATOS GUARDADOS LA CONTRASEÑA SERÁ .23 , .24, .25, .26
	CALL LEEDIG1TEST
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
	CALL CONFIRMA	
	CALL TECLADO	
	CALL EXTRAE
	MOVFW IDENTIFICADOR ;COMPARA QUE EL BIT SEA EL CORRECTO
	XORWF DIG1TEST
	BTFSS STATUS,2 ;EL BIT ES 0? (DIFERENTES?)
	GOTO TESTD1 ;SI NO ES NI EL PRIMERO LA CONTRASEÑA ES INCORRECTA(PERO NO SE MOSTRARA)
	BCF STATUS,2
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
TESTD2
	CALL LEEDIG2TEST
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
	CALL CONFIRMA
	CALL TECLADO
	CALL EXTRAE ;EXTRAE EL NUMERO DEL TECLADO QUE SE PRESIONO
	MOVFW IDENTIFICADOR ;MUEVE EL NUMERO AL IDENTIFICADOR
	XORWF DIG2TEST ;LEE EL VALOR DE DIG2TEST
	BTFSS STATUS,2
	GOTO TESTD2
	BCF STATUS,2
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
TESTD3
	CALL LEEDIG3TEST
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
	CALL CONFIRMA
	CALL TECLADO
	CALL EXTRAE
	MOVFW IDENTIFICADOR
	XORWF DIG3TEST
	BTFSS STATUS,2
	GOTO TESTD3 ;NO
	BCF STATUS,2
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
TESTD4
	CALL LEEDIG4TEST
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
	CALL CONFIRMA
	CALL TECLADO
	CALL EXTRAE
	MOVFW IDENTIFICADOR
	XORWF DIG4TEST
	BTFSS STATUS,2
	GOTO TESTD4 ;NO
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
;-----------
	MOVFW ABRIROADMIN
	XORLW 0X10
	BTFSS STATUS,2
	GOTO CORRECTA ;CORRECTA SE HABRE
	GOTO CAMBIARCONTRA
;------------LECTURA DE EEPROM--------
LEEDIG1TEST
	BSF STATUS,RP1 
	BCF STATUS,RP0 
	MOVLW 0X01
	MOVWF EEADR 
	BSF STATUS,RP0 
	BCF EECON1,EEPGD 
	BSF EECON1,RD 
	BCF STATUS,RP0 
	MOVF EEDATA,W 
	BCF STATUS, RP1
	MOVWF DIG1TEST
RETURN
	
LEEDIG2TEST
	BSF STATUS,RP1 
	BCF STATUS,RP0 
	MOVLW 0X02
	MOVWF EEADR 
	BSF STATUS,RP0 
	BCF EECON1,EEPGD 
	BSF EECON1,RD 
	BCF STATUS,RP0 
	MOVF EEDATA,W 
	BCF STATUS, RP1
	MOVWF DIG2TEST
RETURN
LEEDIG3TEST
	BSF STATUS,RP1 
	BCF STATUS,RP0 
	MOVLW 0X03
	MOVWF EEADR 
	BSF STATUS,RP0 
	BCF EECON1,EEPGD 
	BSF EECON1,RD 
	BCF STATUS,RP0 
	MOVF EEDATA,W 
	BCF STATUS, RP1
	MOVWF DIG3TEST
RETURN
LEEDIG4TEST
	BSF STATUS,RP1 
	BCF STATUS,RP0 
	MOVLW 0X04
	MOVWF EEADR 
	BSF STATUS,RP0 
	BCF EECON1,EEPGD 
	BSF EECON1,RD 
	BCF STATUS,RP0 
	MOVF EEDATA,W 
	BCF STATUS, RP1
	MOVWF DIG4TEST
RETURN



;CUENTA LOS DIGITOS QUE SE HAN INGRESADO
CUENTADIGITOS
	BCF STATUS,2
	MOVFW CONTADORLIMITE
	XORLW 0x03
	BTFSC STATUS,2 ;IGUALES? = 1 DIFERENTES? = 0 ---ES CERO?
	INCF COMPARADORLIMITE,1	;NO
	INCF CONTADORLIMITE,1 ;SI
RETURN

CONFIRMA
	MOVFW COMPARADORLIMITE
	XORLW 0X01
	BTFSC STATUS,2 ;IGUALES? = 1 DIFERENTES? = 0 ---ES CERO?
	GOTO CONTRAINCORRECTA
RETURN

CONTRAINCORRECTA
	MOVLW B'00000' ;DESACTIVO EL CURSOR
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'01100' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA

	CALL LIMPIEZA

	MOVLW B'01000' ;ASIGNO LA PRIMERA LINEA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00101' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA

	CALL CLAVE

	MOVLW B'01100' ;ASIGNO LA SEGUNDA LINEA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00011' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA

	CALL INCORRECTA
	CALL TIEMPO
	CALL TIEMPO
	CALL TIEMPO
	CALL TIEMPO
	CALL TIEMPO
	CALL TIEMPO

GOTO REINICIO

EXTRAE	
	BCF STATUS,2
	MOVFW DIG1
	ADDWF DIG0,0
	ADDWF DIG2,0
	ADDWF DIG3,0
	ADDWF DIG4,0
	ADDWF DIG5,0
	ADDWF DIG6,0
	ADDWF DIG7,0
	ADDWF DIG8,0
	ADDWF DIG9,0
	ADDWF IDENTIFICADOR,1
RETURN

CORRECTA
	CALL CURSOROFF
	CALL LIMPIEZA

	MOVLW B'01000' ;ASIGNO LA PRIMERA LINEA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00100' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA

	CALL CLAVECORRECTA

	CALL TIEMPO
	CALL TIEMPO
	CALL TIEMPO
	CALL TIEMPO
	CALL TIEMPO

	CALL LIMPIEZA
	CALL TIEMPO
	CALL TIEMPO
	MOVLW B'01000' ;ASIGNO LA PRIMERA LINEA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00100' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA

	CALL ABRIENDO

	CALL TIEMPO
	CALL TIEMPO

	CALL PUNTO
	CALL TIEMPO
	CALL PUNTO
	CALL TIEMPO
	CALL PUNTO
	CALL TIEMPO
GOTO REINICIO

LIMPIADIGITOS
	CLRF DIG0
	CLRF DIG1
	CLRF DIG2
	CLRF DIG3
	CLRF DIG4
	CLRF DIG5
	CLRF DIG6
	CLRF DIG7
	CLRF DIG8
	CLRF DIG9
RETURN

CURSOROFF
	MOVLW B'00000' ;DESACTIVO EL CURSOR
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'01100' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
	
;-------MENU------
MENU
	MOVLW 0X10
	MOVWF ABRIROADMIN 
	CLRF DOS_SET
	CALL LIMPIEZA
	GOTO ABRIR
CAMBIARCONTRA
	CALL CAMBIARESTADO
	CALL CURSOROFF
	CALL LIMPIEZA
	CALL NUEVACONTRASEÑA

	;PERMITO EL CURSOR
	MOVLW B'00000' ;ASIGNO LA POSICION DE ESCRITURA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'01111' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	;password
	CALL PASSWORD
	MOVLW B'01100' ;ASIGNO LA POSICION DE ESCRITURA
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00101' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	;LIMPIO LO QUE SE USARÁ PARA EVITAR ERRORES
	BCF STATUS,2
	CLRF DIG0
	CLRF DIG1
	CLRF DIG2
	CLRF DIG3
	CLRF DIG4
	CLRF DIG5
	CLRF DIG6
	CLRF CONTADOR
	CLRF CONTADORLIMITE
	CLRF COMPARADORLIMITE
	BCF STATUS,2
	
	MOVLW 0X00 ;0X00 PARA NUMEROS 0XFF PARA PASSWORD
	MOVWF MODOPASSWORD
SETD1 ;HORA  DE VERIFICAR LOS DATOS GUARDADOS LA CONTRASEÑA SERÁ .23 , .24, .25, .26
	CALL CONFIRMA	
	CALL TECLADO	

	CALL EXTRAE
	;MOVFW IDENTIFICADOR
	;MOVWF DIG1TEST
	MOVFW CONTADORLIMITE
	XORLW 0X01 ;PUEDE VARIAR SI HAY ERRORES
	BTFSS STATUS,2
	GOTO SETD1
	CALL ESCRIBE1
	BCF STATUS,2
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
SETD2
	CALL CONFIRMA	
	CALL TECLADO	
	CALL EXTRAE
	;MOVFW IDENTIFICADOR
	;MOVWF DIG2TEST
	MOVFW CONTADORLIMITE
	XORLW 0X02 ;PUEDE VARIAR SI HAY ERRORES
	BTFSS STATUS,2
	GOTO SETD2
	CALL ESCRIBE2
	BCF STATUS,2
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
SETD3
	CALL CONFIRMA	
	CALL TECLADO	
	CALL EXTRAE
	;MOVFW IDENTIFICADOR
	;MOVWF DIG3TEST

	MOVFW CONTADORLIMITE
	XORLW 0X03 ;PUEDE VARIAR SI HAY ERRORES
	BTFSS STATUS,2
	GOTO SETD3
	BCF STATUS,2
	CALL ESCRIBE3
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR
SETD4
	CALL CONFIRMA	
	CALL TECLADO	
	CALL EXTRAE
	;MOVFW IDENTIFICADOR
	;MOVWF DIG4TEST
	MOVFW CONTADORLIMITE
	XORLW 0X04 ;PUEDE VARIAR SI HAY ERRORES
	BTFSS STATUS,2
	GOTO SETD4
	CALL ESCRIBE4
	CALL LIMPIADIGITOS
	CLRF IDENTIFICADOR

;-----------
	GOTO REINICIO ;CORRECTA SE HABRE

;--------------------EEPROM--------------
ESCRIBE1
	BSF STATUS,RP1 
	BSF STATUS,RP0
E1
	BTFSC EECON1,WR ;Wait for write
	GOTO E1 ;to complete
	BCF STATUS, RP0 ;Bank 2
	MOVLW 0X01 ;Data Memory
	MOVWF EEADR ;Address to write
	BCF STATUS,5
	BCF STATUS,6
	MOVFW IDENTIFICADOR 
	BSF STATUS,6
	MOVWF EEDATA ;to write
	BSF STATUS,RP0 ;Bank 3
	BCF EECON1,EEPGD ;Point to DATA
	;memory
	BSF EECON1,WREN ;Enable writes
	
	BCF INTCON,GIE ;Disable INTs.
	MOVLW 0X55;
	MOVWF EECON2 ;Write 55h
	MOVLW 0XAA ;
	MOVWF EECON2 ;Write AAh
	BSF EECON1,WR ;Set WR bit to
	;begin write
	BSF INTCON,GIE ;Enable INTs.
	BCF EECON1,WREN ;Disable writes
	CLRF STATUS
RETURN
ESCRIBE2
	BSF STATUS,RP1 
	BSF STATUS,RP0
E2
	BTFSC EECON1,WR ;Wait for write
	GOTO E2 ;to complete
	BCF STATUS, RP0 ;Bank 2
	MOVLW 0X02 ;Data Memory
	MOVWF EEADR ;Address to write
	BCF STATUS,5
	BCF STATUS,6
	MOVFW IDENTIFICADOR 
	BSF STATUS,6
	MOVWF EEDATA ;to write
	BSF STATUS,RP0 ;Bank 3
	BCF EECON1,EEPGD ;Point to DATA
	;memory
	BSF EECON1,WREN ;Enable writes
	
	BCF INTCON,GIE ;Disable INTs.
	MOVLW 0X55;
	MOVWF EECON2 ;Write 55h
	MOVLW 0XAA ;
	MOVWF EECON2 ;Write AAh
	BSF EECON1,WR ;Set WR bit to
	;begin write
	BSF INTCON,GIE ;Enable INTs.
	BCF EECON1,WREN ;Disable writes
	CLRF STATUS
RETURN
ESCRIBE3
	BSF STATUS,RP1 
	BSF STATUS,RP0
E3
	BTFSC EECON1,WR ;Wait for write
	GOTO E3 ;to complete
	BCF STATUS, RP0 ;Bank 2
	MOVLW 0X03 ;Data Memory
	MOVWF EEADR ;Address to write
	BCF STATUS,5
	BCF STATUS,6
	MOVFW IDENTIFICADOR 
	BSF STATUS,6
	MOVWF EEDATA ;to write
	BSF STATUS,RP0 ;Bank 3
	BCF EECON1,EEPGD ;Point to DATA
	;memory
	BSF EECON1,WREN ;Enable writes
	
	BCF INTCON,GIE ;Disable INTs.
	MOVLW 0X55;
	MOVWF EECON2 ;Write 55h
	MOVLW 0XAA ;
	MOVWF EECON2 ;Write AAh
	BSF EECON1,WR ;Set WR bit to
	;begin write
	BSF INTCON,GIE ;Enable INTs.
	BCF EECON1,WREN ;Disable writes
	CLRF STATUS
RETURN
ESCRIBE4
	BSF STATUS,RP1 
	BSF STATUS,RP0
E4
	BTFSC EECON1,WR ;Wait for write
	GOTO E4 ;to complete
	BCF STATUS, RP0 ;Bank 2
	MOVLW 0X04 ;Data Memory
	MOVWF EEADR ;Address to write
	BCF STATUS,5
	BCF STATUS,6
	MOVFW IDENTIFICADOR 
	BSF STATUS,6
	MOVWF EEDATA ;to write
	BSF STATUS,RP0 ;Bank 3
	BCF EECON1,EEPGD ;Point to DATA
	;memory
	BSF EECON1,WREN ;Enable writes
	
	BCF INTCON,GIE ;Disable INTs.
	MOVLW 0X55;
	MOVWF EECON2 ;Write 55h
	MOVLW 0XAA ;
	MOVWF EECON2 ;Write AAh
	BSF EECON1,WR ;Set WR bit to
	;begin write
	BSF INTCON,GIE ;Enable INTs.
	BCF EECON1,WREN ;Disable writes
	CLRF STATUS
RETURN
CAMBIARESTADO
	BSF INTCON,GIE ;Enable INTs.
	BCF EECON1,WREN ;Disable writes
CE
	BTFSC EECON1,WR ;Wait for write
	GOTO CE ;to complete
	BCF STATUS, RP0 ;Bank 2
	MOVLW 0X5E ;Data Memory
	MOVWF EEADR ;Address to write
	MOVLW 0X00 ;Data Memory Value
	MOVWF EEDATA ;to write
	BSF STATUS,RP0 ;Bank 3
	BCF EECON1,EEPGD ;Point to DATA
	;memory
	BSF EECON1,WREN ;Enable writes
	
	BCF INTCON,GIE ;Disable INTs.
	MOVLW 0X55;
	MOVWF EECON2 ;Write 55h
	MOVLW 0XAA ;
	MOVWF EECON2 ;Write AAh
	BSF EECON1,WR ;Set WR bit to
	;begin write
	BSF INTCON,GIE ;Enable INTs.
	BCF EECON1,WREN ;Disable writes
	BCF STATUS,5
	BCF STATUS,6
RETURN
;---TECLADO----
TECLADO
	CLRF PORTC
	CLRF PORTB
	BSF PORTB,0
	CALL PREGUNTA1
	CLRF PORTC
	CLRF PORTB
	BSF PORTB,1
	CALL PREGUNTA2
	CLRF PORTC
	CLRF PORTB
	BSF PORTB,2
	CALL PREGUNTA3
	CLRF PORTC
	CLRF PORTB
	BSF PORTB,3
	CALL PREGUNTA4
RETURN
;-PREGUNTAS
PREGUNTA1
	BTFSC PORTB,4
	CALL NUMUNO
	BTFSC PORTB,5
	CALL NUMDOS
	BTFSC PORTB,6
	CALL NUMTRES
RETURN
PREGUNTA2
	BTFSC PORTB,4
	CALL NUMCUATRO
	BTFSC PORTB,5
	CALL NUMCINCO
	BTFSC PORTB,6
	CALL NUMSEIS
RETURN
PREGUNTA3
	BTFSC PORTB,4
	CALL NUMSIETE
	BTFSC PORTB,5
	CALL NUMOCHO
	BTFSC PORTB,6
	CALL NUMNUEVE
RETURN
PREGUNTA4
	BTFSC PORTB,4
	CALL NUMAST
	BTFSC PORTB,5
	CALL NUMCERO
	BTFSC PORTB,6
	CALL NUMGATO
RETURN
;--CONFIRMACIONES
NUMUNO
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	MOVLW .20
	MOVWF UNO_SET

	MOVLW .23	;ASIGNO VALOR PARA LA CONTRASEÑA
	MOVWF DIG1

	BCF STATUS,2
	BCF STATUS,0
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
	CALL _UNO
RETURN
_UNO
	MOVLW B'10011' ;1
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10001'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN
NUMDOS
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	MOVLW .21
	MOVWF DOS_SET
	MOVLW .24	
	MOVWF DIG2 ;ASIGNO VALOR PARA LA CONTRASEÑA
	BCF STATUS,0
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _DOS
RETURN
_DOS
	MOVLW B'10011' ;2
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10010'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO	
RETURN
NUMTRES
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	MOVLW .25	
	MOVWF DIG3 ;ASIGNO VALOR PARA LA CONTRASEÑA

	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _TRES
RETURN
_TRES
	MOVLW B'10011' ;3
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10011'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN
NUMCUATRO
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	MOVLW .26	
	MOVWF DIG4 ;ASIGNO VALOR PARA LA CONTRASEÑA
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _CUATRO
RETURN
_CUATRO
	MOVLW B'10011' ;4
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10100'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN	
NUMCINCO
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	MOVLW .27	
	MOVWF DIG5 ;ASIGNO VALOR PARA LA CONTRASEÑA
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _CINCO
RETURN
_CINCO
	MOVLW B'10011' ;5
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10101'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN
NUMSEIS
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	MOVLW .28	
	MOVWF DIG6 ;ASIGNO VALOR PARA LA CONTRASEÑA
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _SEIS
RETURN
_SEIS
	MOVLW B'10011' ;6
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10110'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN
NUMSIETE
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	MOVLW .29	
	MOVWF DIG7 ;ASIGNO VALOR PARA LA CONTRASEÑA
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _SIETE
RETURN
_SIETE
	MOVLW B'10011' ;7
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10111'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN
NUMOCHO
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	MOVLW .30
	MOVWF DIG8 ;ASIGNO VALOR PARA LA CONTRASEÑA
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _OCHO
RETURN
_OCHO
	MOVLW B'10011' ;8
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11000'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN
NUMNUEVE
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	MOVLW .31	
	MOVWF DIG9 ;ASIGNO VALOR PARA LA CONTRASEÑA
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _NUEVE
RETURN
_NUEVE
	MOVLW B'10011' ;9
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11001'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO	
RETURN

NUMAST
	BCF STATUS,0
	CALL _AST
RETURN
_AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0XFF
	BTFSC STATUS,2 ;
    CALL SUBAST
RETURN
SUBAST
	MOVLW B'10010' ;*
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11010'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN
NUMCERO
	CALL CUENTADIGITOS ;CUENTA LOS CLICKS PARA UN LIMITE DE 4 DIGITOS
	BCF STATUS,0
	BCF STATUS,2
	MOVLW 0XFF		
	MOVWF DIG0 ;ASIGNO VALOR PARA LA CONTRASEÑA
	CALL _AST
	MOVFW MODOPASSWORD ;ASIGNA EL * O 1
	XORLW 0X00
	BTFSC STATUS,2 ;
    CALL _CERO
RETURN
_CERO
	MOVLW B'10011' ;0
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10000'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO	
RETURN
NUMGATO
	MOVLW .33	
	MOVWF DIGGATO ;ASIGNO VALOR PARA LA CONTRASEÑA
	BCF STATUS,0
	MOVLW B'10010' ;#
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10011'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL TIEMPO
RETURN


;-------------------LCD***PALABRAS**NO TOCAR-------------------
NUEVACONTRASEÑA
	CALL N_
	CALL U_
	CALL E_
	CALL V_
	CALL A_	
	MOVLW B'10010' ; ESPACIO
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10000'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL C_
	CALL O_
	CALL N_
	CALL T_
	CALL R_
	CALL A_ ;A
	CALL S_ ;E
	CALL E_
	CALL Ñ_
	CALL A_
RETURN
ABRIENDO
	CALL A_
	CALL B_
	CALL R_
	CALL I_
	CALL E_
	CALL N_
	CALL D_
	CALL O_
RETURN
PUNTO
	MOVLW B'10010' ;.
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11110'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN

CLAVECORRECTA
	CALL C_
	CALL O_
	CALL R_
	CALL R_
	CALL E_
	CALL C_
	CALL T_
	CALL A_
RETURN
CLAVE
	CALL C_
	CALL L_
	CALL A_
	CALL V_
	CALL E_
RETURN
INCORRECTA
	CALL I_
	CALL N_
	CALL C_
	CALL O_
	CALL R_
	CALL R_
	CALL E_
	CALL C_
	CALL T_
	CALL A_
RETURN
MENSAJE
	MOVLW B'00001'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'01100'
	MOVWF PORTC	
	CALL DELAY
	CALL EJECUTA
RETURN
PASSWORD
	CALL P_
	CALL A_
	CALL S_
	CALL S_
	CALL W_
	CALL O_
	CALL R_
	CALL D_
RETURN
HOLASET1
	MOVLW B'01010' ;MENSAJE EN ***HOLA** COMANDO
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'00000'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
;PALABRA HOLA
	CALL HOLA
RETURN

BIENVENIDOSET1
	MOVLW B'01101' ;MENSAJE EN ***HOLA** COMANDO
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'01101'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
;PALABRA HOLA
	CALL BIENVENIDO	
RETURN
LINEAUNO
	MOVLW B'10011' ;1
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10001'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10011' ;>
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11110'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL A_
	CALL B_
	CALL R_
	CALL I_
	CALL R_
RETURN
LINEADOS
	MOVLW B'10011' ;2
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10010'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10011' ;>
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11110'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	CALL A_
	CALL D_
	CALL M_
	CALL I_
	CALL N_
RETURN


BIENVENIDO
	CALL B_
	CALL I_
	CALL E_
	CALL N_
	CALL V_
	CALL E_
	CALL N_
	CALL I_
	CALL D_
	CALL O_
	BCF STATUS,0
RETURN
HOLA
	CALL H_
	CALL O_
	CALL L_
	CALL A_
	BCF STATUS,0
RETURN
INIT
	CALL DELAY
	CALL DELAY
	BCF RS
	MOVLW B'0011' ;1
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'0011'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'0011' ;2
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'0010'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'0010' ;3
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'1000' 
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'0000' ;4
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'1100'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'0000' ; LIMPIA EL DISPLAY
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'0001'
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
A_
	MOVLW B'10100' ;A
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10001'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
B_
	MOVLW B'10100' ;B
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10010'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
R_
	MOVLW B'10101' ;R
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10010'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
I_
	MOVLW B'10100' ;I
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11001'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
E_
	MOVLW B'10100' ;E
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10101'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
N_
	MOVLW B'10100' ;N
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11110'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
D_	MOVLW B'10100' ;D
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10100'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA

RETURN
O_
	MOVLW B'10100' ;O
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11111'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
S_
	MOVLW B'10101' ;S
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10011'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
L_
	MOVLW B'10100' ;L
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11100'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
H_
	MOVLW B'10100' ;H
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11000'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN

C_
	MOVLW B'10100' ;C
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10011'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
T_
	MOVLW B'10101' ;T
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10100'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
V_
	MOVLW B'10101' ;V
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10110'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
U_
	MOVLW B'10101' ;U
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10101'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
Ñ_
	MOVLW B'11110' ;Ñ
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11110'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
M_
	MOVLW B'10100' ;M
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'11101'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
W_
	MOVLW B'10101' ;W
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10111'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN
P_
	MOVLW B'10101' ;P
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
	MOVLW B'10000'	
	MOVWF PORTC
	CALL DELAY
	CALL EJECUTA
RETURN




EJECUTA
	BSF EN
	CALL DELAY
	BCF EN
	CALL DELAY
	CLRF PORTC
RETURN
LIMPIEZA
	;LIMPIO TOTALMENTE EL LCD
	CLRF PORTC
	CLRF PORTB
	MOVLW B'00000'
	MOVWF PORTC
	CALL EJECUTA
	CALL DELAY
	MOVLW B'00001'
	MOVWF PORTC
	CALL EJECUTA
	CALL DELAY
	MOVLW B'00000'
	MOVWF PORTC
	CALL EJECUTA
	CALL DELAY
	MOVLW B'00010'
	MOVWF PORTC
	CALL EJECUTA
	CALL DELAY
	;FIN DE LA LIMPIEZA
RETURN
;RETARDO PRINCIPAL
DELAY
	MOVLW TMR_CARGA
	MOVWF TMR0
	BCF INTCON,T0IF
TIMER_DESBORDE
	BTFSS INTCON,T0IF
	GOTO TIMER_DESBORDE
	RETURN


;retardo por ciclos
TIEMPO
	MOVLW .2	
	MOVWF 0x23
TRES
	MOVLW .100
	MOVWF 0X24
DOS
	MOVLW .249
	MOVWF 0X25
UNO
	NOP
	DECFSZ 0X25
	GOTO UNO
	DECFSZ 0X24
	GOTO DOS
	DECFSZ 0X23
	GOTO TRES
RETURN


END
